name = "Tinkerer's Quilt Modded (1.20)"
author = "Sisby folk"
version = "4.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bff5d6fc40ecc0504f41149eed0bbe2df5e2aee849d684bf90f8a174c41a7a02"

[versions]
minecraft = "1.20.1"
quilt = "0.29.0-beta.7"
unsup = "1.1.3"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
datapack-folder = "/resources/datapacks/"
resourcepack-folder = "/resources/resourcepacks/"
