name = "Tinkerer's Quilt Garden (1.20)"
author = "Sisby folk"
version = "4.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c20305825fe4ca0d27d0198e0a45ddc749d8defc11b64fd760a10f5f6b327457"

[versions]
minecraft = "1.20.1"
quilt = "0.28.0-beta.5"
unsup = "0.3.0-rc2.pre1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
datapack-folder = "/resources/datapacks/"
resourcepack-folder = "/resources/resourcepacks/"
