name = "Tinkerer's Quilt Plus (1.20)"
author = "Sisby folk"
version = "4.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b2f8fc46ecc01ebb347d37ee0b5b5b84ed0c3413e6d96fd8f5fb5605f2e1adae"

[versions]
minecraft = "1.20.1"
quilt = "0.29.0-beta.7"
unsup = "1.1.3"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
datapack-folder = "/resources/datapacks/"
resourcepack-folder = "/resources/resourcepacks/"
